package com.example.musala.utils;

import java.security.SecureRandom;

public class ByteArrayGenerator {
    public static void main(String[] args) {
        // Define the length of the byte array
        int length = 10; // Specify the desired length of the byte array

        // Generate a byte array of specified length
        byte[] byteArray = generateRandomByteArray(length);

        // Print the generated byte array
        System.out.println("Generated Byte Array:");
        for (byte b : byteArray) {
            System.out.print(b + " ");
        }
    }

    // Method to generate a random byte array of a specified length
    private static byte[] generateRandomByteArray(int length) {
        byte[] byteArray = new byte[length];

        SecureRandom secureRandom = new SecureRandom();
        secureRandom.nextBytes(byteArray);

        return byteArray;
    }
}